### ISSUE TITLE
Elm Formatting

### ISSUE THREAD

**Issue by churchie317** [exercism/elm#195] opened 2018-02-13 23:49 UTC
Not a huge deal, but [this](https://github.com/exercism/elm/commit/a21249c484915195892b395e6bd4c68c0a4d2ee0) commit appears to have [broken](https://travis-ci.org/exercism/elm/builds/341146782) the build, due to formatting.

I'm not sure if this is because the user was using an old version of elm-format or the build script uses an older version of format.

Do we know if this pipeline is part of the deploy process?

**Comment by neganp** [comment] 2018-02-14 00:05
Aw shoot, I merged that, assuming that elm-fmt gets checked. I guess it doesn't if the build is broken 😕. My bad.

**Comment by churchie317** [comment] 2018-02-14 00:48
No worries!

Not sure why it would have passed the first time and not the second, but it should be a relatively trivial fix.

**Comment by neganp** [comment] 2018-02-14 01:01
Maybe master changed bbc between checks? I'll look at it when I get back to
a laptop if it hasn't been fixed already.

**Comment by neganp** [comment] 2018-02-15 20:16
#196 should fix this issue. I think the original break was caused when we upgraded to `elm-format` 0.7: the original CI check must have been done with the previous version of `elm-format`, or perhaps a cached build environment--it could be a number of things. In any case, if this fix works and it doesn't happen again, I don't think it's worth tracking down a root cause.

**Closed** 2018-02-15 22:18 UTC
Labels: bug

**Comment by churchie317** [comment] 2018-02-16 00:10
🙌  Thanks for taking care of this!
